version: '3.8'

x-common-variables: &common-variables
  MYSQL_DATABASE: stockdb
  MYSQL_USER: user
  MYSQL_PASSWORD: password

services:
  mysql_db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
      - mysql-data:/var/lib/mysql
    ports:
      - "9906:3306"
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: password
      MYSQL_HOST: localhost

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "7000:80"
    environment:
      MYSQL_ROOT_PASSWORD: password
      PMA_HOST: mysql_db
      PMA_USER: root
      PMA_PASSWORD: password

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    depends_on:
      - mysql_db
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - 3001:3001
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql_db

  client:
    stdin_open: true
    ports:
        - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client

  adminer:
      image: adminer:latest
      restart: unless-stopped
      ports:
        - 8000:8080
      depends_on:
        - mysql_db
      environment:
        ADMINER_DEFAULT_SERVER: mysql_db

volumes:
  mysql-data:
    driver: local
